# Generated by Django 5.0 on 2024-06-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titles', models.CharField(max_length=25)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
    ]
